### ISSUE TITLE
React.forwardRef() warning when using WithStore

### ISSUE THREAD

**Issue by caterinavanherpt** [express-labs/pure-react-carousel#138]
I have wrapped my component with the WithStore component but I am getting the following warning: 

Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()? Check the render method of `n`.

I am still able to access the state as props in my child components but wondering how to fix the error above.

**Comment by bcarroll22** [comment]
👋 hi Caterina. This problem is because by default you can't pass a ref on to a functional component. Traditionally, this has been one of the pain points of using a functional component. Based on the warning message though, this looks like something you can take care of with your version of React. Once option would be to simply refactor your component to a class component, but I think that's likely not necessary. You should try this:

```
const YourComponent = React.forwardRef(({}, ref) => (
  <div>
    // you may or may not need to use the forwarded ref
  </div>
))

export default WithStore(MyComponent);
```

For reference, [here's the React documentation on `forwardRef`](https://reactjs.org/docs/forwarding-refs.html)

Good luck!

**Comment by caterinavanherpt** [comment]
Hi Brandon. Thanks for the suggestion. That worked to clear the warning.

**Comment by graysonhicks** [comment]
I am getting this error as well, but the `MyComponent` is a class component.  `MyComponent` does have some functional components above and below it in the component tree, but I do not have any explicit references to `ref`.

 I even refactored `MyComponent` to a functional component with `forwardRef` with no luck.
