### ISSUE TITLE
Image component with 'isBgImage={true}' causing console warning

### ISSUE THREAD

**Issue by pragmatic84** [express-labs/pure-react-carousel#156]
Hello again,

As the title implies, when i set the aforementioned prop to true I get this console warning. It's not the end of the world and nothing breaks but was just curious to know if there was a better solution?

![Screenshot 2019-06-27 at 16 43 03](https://user-images.githubusercontent.com/7489089/60280425-d25bfa80-98fa-11e9-9ca2-201544ff234f.png)

**Comment by mrbinky3000** [comment]
Sounds like you're trying to set a background image on an actual `<img />` tag.  By default, our Image component creates an img tag. There is a `tag` option on the Image component that lets you render something like a DIV instead of an IMG tag.  The option `isBgImage` was intended for adding an image to tags like DIV.   IMG tags are already images.

I can update the docs to make this more obvious.
