### ISSUE TITLE
Add in README the link to example source code

### ISSUE THREAD

**Issue by stephane-klein** [express-labs/pure-react-carousel#189]
Hi,

where is the example source code (https://express-labs.github.io/pure-react-carousel/) ?

I suggest to add link to this source code in [README](https://github.com/express-labs/pure-react-carousel/blob/master/README.md).

Best regards,
Stéphane

**Comment by stephane-klein** [comment]
Demo is here https://github.com/express-labs/pure-react-carousel/tree/master/src/App

**Comment by bcarroll22** [comment]
Hi @stephane-klein, in the future can you please use one of the provided issue templates? It really makes it easier for us to sort and track the open issues.

I'm going to go ahead and close this now since it looks like you've found what you're looking for. If you'd like for something to be added to the README or documentation, please feel free to [make a pull request](http://makeapullrequest.com/) to add it. We'd be happy to add you as a [contributor](https://github.com/express-labs/pure-react-carousel#contributors-) on the project for your time.

Good luck!
