### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by brunnolou** [express-labs/pure-react-carousel#19]
Please provide an online demo, it's very important when deciding which carousel to chose.

**Comment by tim-steele** [comment]
Currently you can download and run `npm start` and you can see a demo of it.

We will work on getting a GitHub pages demo set up for the future.

**Comment by mrbinky3000** [comment]
Keep in mind that Pure React Carousel is a collection of minimally styled components.  It's up to you to apply the css styles that meet your needs.  

You can see a working version of the carousel here:  
https://www.express.com/clothing/women/karlie-kloss-minus-the-leather-cropped-bralette-tank/pro/08633275/cat3520003

**Comment by mikhuang** [comment]
1) the command seems to be `npm run dev`
2) the demo currently doesn't seem to work. style.css 404s. I'm not super familiar with how rollup and wasn't able to resolve. After injecting `react-carousel.es.css` into <head> with a style tag (yay DOM inspector), everything looks fine.

**Comment by rjacobson16** [comment]
I'm having major issues resizing my carousels. 

>_slide_fhwgk_1._slideHorizontal_fhwgk_1.carousel__slide won't respond to any resizing. Could and setting the natural Slide Height and width is not working. Is there a styling guide?

**Comment by mrbinky3000** [comment]
@rjacobson16 pure react carousel only adds the bare-minimum CSS required to function.  All other styling, including the size of your carousel, needs to be added by you.  You can either wrap your carousel in a div and set the css max-width, or you can add your own css class to the \<Slider /> component to contain the width of your carousel.

The natural slide height and width are used to set a ratio of height to width, they are not actual pixel height and with.  All the slides are, by default, responsive, meaning they will expand to the full width of the screen unless contained.  They will also shrink down to the smallest mobile device.

Just a reminder.  This is not an out-of-the-box turn-key carousel solution.  This project was created because I found other carousels set too many css styles that I had to defeat in order to match the style guide for a client.  You will have to apply css styles to many of the pure-react-carousel components in order to get them to look the way you desire. 

Let me know if you need any more help.

**Comment by StephanBijzitter** [comment]
>The natural slide height and width are used to set a ratio of height to width, they are not actual pixel height and width. All the slides are, by default, responsive, meaning they will expand to the full width of the screen unless contained. They will also shrink down to the smallest mobile device.

This is not clear from the documentation, and perhaps (if this is only used as a ratio) it could be combined into a single prop: `aspect-ratio={16 / 9}`.

**Comment by mrbinky3000** [comment]
@brunnolou we now have a gh page.  #108 

https://express-labs.github.io/pure-react-carousel/
