### ISSUE TITLE
Infinite loop, direction change when you reach the end.

### ISSUE THREAD

**Issue by danielbotn** [express-labs/pure-react-carousel#192]
The new "infinite" prop for <CarouselProvider> introduced in version 1.23.0 is a very nice feature, but I was wondering if it would be possible to change the direction when the user has reached the end of the slides. So instead of going left all the way to the beginning, you would go to the right and end up at the beginning.
Like in the examples shown here: "https://kenwheeler.github.io/slick/"

**Comment by bcarroll22** [comment]
Hi @danielbotn we’re gonna go ahead and close this issue and ask that you re-open with one of the provided issue templates. That helps us manage and track our issues internally.

To save you some time when you do re-open, since this is a feature request, we’ll likely ask that you implement the suggested feature by making a PR.

Thanks!
