### ISSUE TITLE
How do you know the naturalSlideHeight  and naturalSlideWidth for elements?

### ISSUE THREAD

**Issue by maxxims** [express-labs/pure-react-carousel#194]
Hello,

How do you calculate the naturalSlideHeight and Width if I can add any element type inside my slider.
Let's say I have 5 div elements, how do I know what to pass to the <CarouselProvider>?

Thank you!

**Comment by bcarroll22** [comment]
Hello, please reopen this using the provided issue templates. If the reason you didn’t use a template is that this is a question, please use the suggested approaches in the question template. As stated in that template, issues opened that are questions will be closed since this is intended to be an issue tracker, not
