### ISSUE TITLE
Сarousel without tight binding to number of slides

### ISSUE THREAD

**Issue by KickAce** [express-labs/pure-react-carousel#201]
Hello,

How can i do carousel without binding to number of visible slides, only set width each all slides?

Thank you!

**Comment by bcarroll22** [comment]
Hi @KickAce, thanks for using pure-react-carousel!

As we outline in the issue templates, this is a tracker for bugs and feature requests, not a place for support or questions, so I’m gonna have to close this. Sorry we can’t help out more, the best advice I can give you is check out the docs or ask somewhere like StackOverflow. 

If after that you’d still like to request a feature or report a bug, feel free to fill out another issue using one of the provided templates. I’m going to go ahead and close this now since it’s neither a bug report nor feature request. In the future, please stick to one of the provided templates, it really helps us track and manage issues. 

Good luck! 👍
