### ISSUE TITLE
no (or less) space between Slides

### ISSUE THREAD

**Issue by filenda** [express-labs/pure-react-carousel#226]
![image](https://user-images.githubusercontent.com/16693247/71328540-8f6c8f80-24f7-11ea-9269-034e8e25fb53.png)

Can I do just a simple div with background image wrapped inside an anchor (just like the print bellow) using any native props of the components?

**Comment by cjayross** [comment]
+1 This would be really handy for my use case.

**Comment by mrbinky3000** [comment]
You can achieve this.  There is nothing preventing you from putting whatever content you want inside of each carousel cell and formatting however you desire.  It's one of the main goals of the project to be highly customizable.  There are currently plenty of ways to pass the CSS that you will have to write to the various components.  Each component has a className prop where you can pass in your own sass.  There are also hard-coded class names so you can write vanilla CSS.  This really isn't an issue.  You'll have to play around and figure it out.

**Comment by cjayross** [comment]
You're probably write @mrbinky3000. Though it does require one to learn the inner mechanics of how the carousel operates since I have noticed that adding margins to slides screws up your slider since the slider's width is calculated only using the natural widths passed to the provider. Additionally, since adding a margin to the left of the first slide can screw up how slides align relative to other components, dealing with the special cases can be a hassle to do manually. It's not impossible, but perhaps a way to make it more convenient would be nice.

**Comment by SilencerWeb** [comment]
Yeah, archiving this behavior should be out of the box

@mrbinky3000, by the way, there isn't really an easy way to do it. Would be awesome if you could show us these magic CSS lines that will produce such behavior otherwise it will be an issue, don't you think? 🙂
