### ISSUE TITLE
Variable sized content

### ISSUE THREAD

**Issue by mikhuang** [express-labs/pure-react-carousel#23]
Hi there,

Just wondering, is there any plan to allow the slideshow figure out height (or adjust height depending on current slide) for when the height of the slide content is unknown?

Thanks!

**Comment by mrbinky3000** [comment]
Keep in mind:
- The carousel is responsive by default.  That means the &lt;Slide> component will stretch or shrink to fill the width of the &lt;Slider> component. The height of the &lt;Slide> component will shrink or grow based on the ratio of the naturalSlideWidth to natrualSlideHieight properties that you set on &lt;Slider>.
-  All the slides have to be the same size in order for this carousel to work.   So, the height can't change based on the slide.  

**Solutions**
Are you using the &lt;Image> component?  If so, set the tag attribute to "div" and isBgImage to true, this will force the image to be loaded into the background.  The background image will flex to "cover" the entire div, so some clipping might occur if your images are different sizes.  So, in your case, change the background-size to "contain".  Look up more 

```
<Image 
  src="../myimage.jpg" 
  tag="div" 
  isBgImage 
  style={{backgroundSize: 'contain'}} 
/>
```

I still need to add more documentation for the Image component. My apologies.

If you're not using the Image component and just using a plain &lt;img> element then style your img element to be responsive and "flex".  The innermost div of the &lt;Slide> component has both the width and height set to 100%, that means whatever img tag you place inside the slide component can have a width set to 100% or the height set to 100%.  
- If you care about the height over the width, then set the height to 100% and leave the width blank.  - If you care about the width over the height, then set the width to 100% and leave the height alone. 

Your best bet is to use the Image component example from above.

I might change the default value for the backgroundSize to be 'contain' instead of 'cover'

**Comment by mikhuang** [comment]
Thank you for the super detailed response! My particular use case is text of varying lengths. Thus a fixed aspect ratio seems inadequate. I ended up using react-slick for their auto height feature (it looks a bit janky since the height just jumps without animation but eh). It's possible I'll be better served by deciding on a max length of text and using a fixed aspect ratio (or rather several for the different screen widths) but that isn't in scope for me now.

**Comment by mrbinky3000** [comment]
You could put the text in a div that is 100% height and then set overflow to auto?  However, vertical scrolling text in a horizontal scrolling carousel sounds like something a marketing director would come up with ;-)
