### ISSUE TITLE
Continuous sliding in one direction

### ISSUE THREAD

**Issue by jozefcipa** [express-labs/pure-react-carousel#251]
Hi, first of all, I really like the project and I'm happy I finally found a pure react implementation without jquery 😂

**Describe the feature you'd like:**
I find it inconvenient that every time I reach the last slide the next button gets disabled and I need to go through all the slides back if I want to get to the beginning. I would appreciate it if there was an option to set continuous sliding so then after clicking the next button on the last slide it would go to the first one again. Same with infinite scrolling. After it hits the last slide it goes back in reverse order instead of just continuing in the same order to the first slide again.
What do you guys think? I could potentially work on this feature if you acknowledge it's useful and considerable.

P.S. I noticed there was a similar issue closed https://github.com/express-labs/pure-react-carousel/issues/192. So I'm wondering if it is already implemented and I just overlooked it somehow or is it still relevant?

**Comment by jdconner** [comment]
@jozefcipa There is an `infinite` prop that you can use, though, it will merely reset the scroll rather than look as though it was continuous. It was added to make the UX better for the time being until someone had the time to make it seem continuous. See https://github.com/express-labs/pure-react-carousel/pull/187

**Comment by georgemarshall-** [comment]
@jozefcipa Would like to see this feature too!

**Comment by dons20** [comment]
Bump, only reason I can't utilize this library right away because my projects require seamless infinite scrolling.

**Comment by cjayross** [comment]
+1 Definitely would like to have this.

**Comment by Hagafny** [comment]
Agreed, We would not be able to use this component in our project because we need to have a seamless infinite scrolling.

**Comment by jdconner** [comment]
Based on previous conversations, the underlying owners of the repo do not require this feature so they will not be building it. If anyone wants to contribute, I'm sure they will be glad to review 🙂 (Express, feel free to correct if I'm wrong)

**Comment by Hagafny** [comment]
That's a shame. Really loved the component and it's very close to being complete, but without this feature I believe a lot of users will have second thoughts.

Guess I'll have to go back to react-slick for now

**Comment by drewpoling2** [comment]
I achieved this functionality if anyone still needs a solution. I don't have a PR for this component, but here are the steps I took in my project. My solution below should give you an infinitely scrolling slider in one direction without jumping back to the beginning after you've cycled through all the slides. First I started off with the base setup given in the component docs. Next I began by -

1. Setting state and context variables

I did this by: 
```
const ArticleGalleryContent = ({ data: { slidesData, title } }) => {

  const numSlides = slidesData.length;
  const carouselContext = useContext(CarouselContext);
  const [currentSlide, setCurrentSlide] = useState(
    carouselContext.state.currentSlide
  );

//more added here
}

```

2. Disable slide animation on Slider component. This is necessary to give the illusion that you are infinitely looping through the slides without jumping back to the beginning. 

I did this by:
- adding `id=slider_element` onto my <Slider/> component
- then removing animation 
```
#slider_element > div > div {
  transition: 0s ease-in-out !important;
}
```
- the way you target this child to remove the animation may be different in your project depending on if you've added elements in between. 

3. Next push the slides into an array. Two loops are required here. The purpose of this is to create clones on the sides of the slides that you will be looping through. These clones will allow there to always be a slide on the left and right ends of the slider, thus avoiding any white space. This along with removing the animation with give the illusion of an infinite loop. 

```
const slides = [];

   for (let j = 0; j < 2; j++) {
    for (let i = 0; i < slidesData.length; i++) {
      slides.push(
        <Slide
          className={styles.slide}
          classNameHidden={styles.hiddenSlide}
          classNameVisible={'article-gallery__visible'}
          index={j === 0 ? i : j === 1 ? 3 + i : 'null'}
          key={`slide${j}-${slidesData[i].index}`}
          tabIndex={-1}
        >
          <ArticleGalleryImage {...slidesData[i]} />
        </Slide>
      );
    }
  }
```
- Your classNames will be different in your project. 

6. Used basic <button><button/> components instead of <ButtonBack/> & <ButtonNext/>. This is needed to avoid the built in onClick functionality in the ButtonBack & ButtonNext components. This way you can control functionality of what slides you want to translate to and under what conditions. 

I did this by: 
- creating onClicks for each button

```
  const handleNext = () => {
    if (slidesData && currentSlide === slidesData.length) {
      carouselContext.setStoreState({ currentSlide: slidesData[1].index });
    } else {
      carouselContext.setStoreState({
        currentSlide: currentSlide + 1,
      });
    }
  };

  const handleBack = () => {
    if (slidesData && currentSlide === slidesData[1].index) {
      carouselContext.setStoreState({ currentSlide: numSlides });
    } else {
      carouselContext.setStoreState({
        currentSlide: currentSlide - 1,
      });
    }
  };

```
- then adding onClicks to each button ```
    <button onClick={handleBack}></button> 
      <div style={{ display: 'flex', flexDirection: 'row' }}>
        <Slider
          className={styles.slider}
          classNameTray={`${styles['sliderTrayCount' + numSlides]}`}
          tabIndex={-1}
          role="" 
          trayProps={{
            role: 'listbox',
            'aria-label': 'gallery',
          }}
          id="slider_element"
        >
          {slides}
        </Slider>
      </div>
    <button onClick={handleNext}></button>
```

- these onClicks will increment the slide to the next or previous slide unless they are next to the end of the loop. If this condition is met, they will jump to a clone slide which is not at the end of the slider tray. 

And there you have it. This should give you an infinitely scrolling slider in one direction without jumping back to the beginning after you cycled through all the slides.

**Comment by kashanshah** [comment]
@drewpoling2 can you show a codepen?
