### ISSUE TITLE
Expose Carousel Context/Store via Render Prop/Function

### ISSUE THREAD

**Issue by esr360** [express-labs/pure-react-carousel#270]
Hello - this Carousel is great! Well done.

I just have one strong request that would really improve the experience for me.

I'm using the Carousel components like so:

```jsx
import { CarouselProvider, Slider, Slide, ButtonBack, ButtonNext, Dot } from 'pure-react-carousel';
import 'pure-react-carousel/dist/react-carousel.es.css';

import config from './assets/config';
import styles from './assets/styles';

const Carousel = ({ slides, options, ...props }) => {
  const { name } = useConfig(props);

  return (
    <Module name={name} as={CarouselProvider} naturalSlideWidth={16} naturalSlideHeight={9} totalSlides={3} {...props}>
      <Component name='slider' as={Slider}>
        { slides.map((slide, index) => (<Component name='slide' as={Slide} index={index} key={index} content={slide} />)) }
      </Component>

      <Component name='navigation'>
        <Component name='control' as={ButtonBack}>Back</Component>
        <Component name='control' as={ButtonNext}>Next</Component>
      </Component>

      <Component name='pager'>
        { slides.map(($, index) => (<Component name='dot' as={Dot} slide={index} key={index} />)) }
      </Component>
    </Module>
  );
}

Carousel.defaultProps = { config, styles }

export default Carousel;
```

...and I need access to the `currentSlide` property. Using either the `withStore` HOC or `useContext` hook would be quite awkward for my setup I think.

What would be super convenient for me would be being able to access the store/context values as via a render prop/function, something like:

```jsx
const Carousel = ({ slides, options, ...props }) => {
  const { name } = useConfig(props);

  return (
    <Module name={name} as={CarouselProvider} naturalSlideWidth={16} naturalSlideHeight={9} totalSlides={3} {...props}>
      {({ currentSlide }) => (
        ...
      )}
    </Module>
  );
}
```

...or:

```jsx
const Carousel = ({ slides, options, ...props }) => {
  const { name } = useConfig(props);

  return (
    <Module name={name} as={CarouselProvider} render={({ currentSlide }) => (
      ...
    )} naturalSlideWidth={16} naturalSlideHeight={9} totalSlides={3} {...props} />
  );
}
```

...what are your thoughts here? If agreeable to the feature I could work on a PR.

Thanks.

**Comment by esr360** [comment]
For what it's worth, I was able to achieve what I wanted with the following:

```jsx
const Carousel = ({ slides, options, ...props }) => {
  const { name } = useConfig(props);

  const Render = WithStore(({ currentSlide }) => (
    <Module name={name} {...props}>
      <Component name='slider' as={Slider}>
        { slides.map((slide, index) => (
          <Component name='slide' as={Slide} onFocus={() => setActiveSlide(index)} index={index} key={index} content={slide} />
        )) }
      </Component>

      <Component name='navigation'>
        <Component name='control' as={ButtonBack}>Back</Component>
        <Component name='control' as={ButtonNext}>Next</Component>
      </Component>

      <Component name='pager'>
        { slides.map(($, index) => <Component name='dot' as={Dot} active={currentSlide === index} slide={index} key={index} />) }
      </Component>
    </Module>
  ), state => ({ currentSlide: state.currentSlide }));

  return (
    <CarouselProvider naturalSlideWidth={16} naturalSlideHeight={9} totalSlides={3}>
      <Render />
    </CarouselProvider>
  );
}
```

**Comment by esr360** [comment]
For what it's worth I've been able to achieve what I want by using Refs and useEffect:

```jsx
const MyComplexCarousel = ({ slides, ...props }) => {
  const { name } = useConfig(props);
  const provider = React.useRef();
  const [currentSlide, setCurrentSlide] = useState(0);

  React.useEffect(() => {
    const { carouselStore } = provider.current;
  
    carouselStore.subscribe(() => setCurrentSlide(carouselStore.state.currentSlide));
  }, []);

  return (
    <Module name={name} as={CarouselProvider} host={provider} {...props}>
      <Component name='slider' as={Slider}>
        {slides.map((slide, index) => (
          // We continue to pass the `pure-react-carousel` Components via `as`
          <Component name='slide' as={Slide} index={index} content={slide} />
        ))}
      </Component>

      <Component name='navigation'>
        <Component name='control' as={ButtonBack}>Back</Component>
        <Component name='control' as={ButtonNext}>Next</Component>
      </Component>

      <Component name='pager'>
        {slides.map(($, index) => (
          // Here you can see we make use of the `currentSlide` value
          <Component name='dot' as={Dot} active={currentSlide === index} slide={index} />
        ))}
      </Component>
    </Module>
  );
}
```

**Comment by delewis13** [comment]
Bump & agree - ability to use a render function would be great. Same use-case regarding needing access to currentSlide

**Comment by esr360** [comment]
@mrbinky3000 (sorry if you are not the correct person to tag) - with respect, I implore you to remove this stale bot, I don't really understand why you set it up to close issues before anyone from the team has even addressed them?

**Comment by tim-steele** [comment]
@esr360 I am glad you have suggestions about this project. One of the things we request when opening an issue is to use one of our templates. We have one for feature requests for features specific to this. Part of the feature request is to answer some questions around the feature. In this instance, you have thought of an alternative, but a good discussion would be why a render prop would be more ideal. Ultimately, by making the case we will ask for you to submit a PR (and when merged at you as a contributor to the front page of the project).

We have stale bot because we receive a number of Issues opened for:
- Questions that are answered in the documentation
- Problems that may or may not be related to this carousel
- Issues that don't follow our template and are missing information
- Support questions for help debugging a project.

As much as we would like to be able to answer, help, and give everyone time and attention, that is just not realistic. We have jobs that we must attend to, and families that we go home to. Ultimately, we built this as a way to have a carousel that is un-opinionated and built in React, something that didn't exist at the time. We open-sourced it to share the work we did with the community.

If this render prop is something you are still looking to do, and you have a good case for it, please open up a PR so we can discuss and work on it. Even if it is just a draft PR to start the conversation.
