### ISSUE TITLE
Cannot restyle dot width below 16px

### ISSUE THREAD

**Issue by Steve-Reid** [express-labs/pure-react-carousel#278]
- `pure-react-carousel` version: 1.27.1
- `react` version: 16.13.0
- `browser` used: chrome
- `node` version: 12.16.2

### Relevant code or config:

```js
            '& .carousel__dot': {
                backgroundColor: '#C4C4C4',
                height: '10px',
                width: '10px',
                borderRadius: '50%',
                margin: '0 12px',
                boxSizing: 'content-box',
            },
```

### What you did: 

Targeted the dot/button within DotGroup

### What happened:

Dot displays at a minimum width of 16px ignoring the rule.

**Comment by Darthmaul** [comment]
Hi @tim-steele 

Sorry to ping you, but I am trying to work with this library and the only issue I really have is the one  described here. The library works perfectly for what I need, but my requirements are that our dots need to be 8px by 8px.

For some reason, the dots are not able to be styled width less than 16px. 

Do you have any idea why the width would be constrained in this way?

**Comment by tim-steele** [comment]
@Darthmaul I don't know why they are restrained this way. I can take a look at it when I get a chance. I think you can also use your own dots if you want them to be different. 

Looking at the demos, there is no width applied to the dots/buttons. It is padding. Since it is (6px padding + 2px border) * 2 sides, you get 16px. You need to reduce the padding to reduce the width.

![image](https://user-images.githubusercontent.com/1490225/98004534-0f24e500-1dbe-11eb-9413-f12ff1d5af15.png)

**Comment by Darthmaul** [comment]
Hi, thanks for the response. I ended up having to pivot to a different library to enable the functionality given my time constraints. If I need to implement again, I will attempt your fix described here. 

Preciate it! 👍
