### ISSUE TITLE
Not working with react-redux

### ISSUE THREAD

**Issue by matpaul** [express-labs/pure-react-carousel#28]
If my slide content is connected component it's fails because CarouselProvider have own store in context

**Comment by mrbinky3000** [comment]
Sorry for the delay. 

I'll have to create a small demo using react-redux in order to debug this one.  If your project is a public project on GitHub, perhaps you can point me to the repo so I can fork it and play around.  It would save me some time.  

If not, no biggie.

Can you paste a little code snippet to show me how you are wiring up the slide content to react-redux?

**Comment by matpaul** [comment]
We need some slide content component that connected to redux
```jsx
// Component.js
const ConnectedComponent = ({name}) => <div>{name}</div>;

const mapStateToProps = (state) => ({ name: state.user.name });
// connect use store (redux)  in context provided by Provider component
export default connect(mapStateToProps)(ConnectedComponent)

// App.js
// just take code from example
class ComponentWithCarousel extends React.Component {
...
render() {
    // CarouselProvider provide own store (carousel store) so error occure 
    return (
      <CarouselProvider 
        naturalSlideWidth={100}
        naturalSlideHeight={125}
        totalSlides={3}
      >
        <Slider>
          { slidesArray.map((slide, index) => (
            <Slide index={index} key={slide.id}>
               <ConnectedComponent />
             </Slide>
           )}
        </Slider>
      </CarouselProvider>
    );
  }
}

**Comment by mrbinky3000** [comment]
Haven't forgotten about you!   I'll have some time later in the week.

**Comment by mrbinky3000** [comment]
@matpaul v1.9.8 should resolve your issue.

**Comment by matpaul** [comment]
Cool, thank you! 💪🏻
