### ISSUE TITLE
Hooks and useContext 

### ISSUE THREAD

**Issue by AgtLucas** [express-labs/pure-react-carousel#291]
Hi all,

Thanks for doing this project!

Am I missing something or the usage `CarouselContext` with hooks aren't supported yet?

I follow the example on the [README](https://github.com/express-labs/pure-react-carousel#hooks-and-usecontext) file, but it looks like `CarouselContext` it's empty: https://github.com/express-labs/pure-react-carousel/blob/master/src/CarouselProvider/context.js#L3

I did exactly as it says:

```js
import React, { useContext, useEffect, useState } from 'react';
import { CarouselContext } from 'pure-react-carousel';

export function MyComponentUsingContext() {
  const carouselContext = useContext(CarouselContext);
  const [currentSlide, setCurrentSlide] = useState(carouselContext.state.currentSlide);
  useEffect(() => {
    function onChange() {
      setCurrentSlide(carouselContext.state.currentSlide);
    }
    carouselContext.subscribe(onChange);
    return () => carouselContext.unsubscribe(onChange);
  }, [carouselContext]);
  return `The current slide is: ${currentSlide}`;
}
```

But this constant `carouseContext` is returning `undefined`:

```js
const carouselContext = useContext(CarouselContext); // it returns undefined
```
Any ideas why?

Thanks!

**Comment by misshu1** [comment]
Hello, my guess is the problem with the <CarouselProvider /> you can't use the context and the provider in the same component, move the provider one level up, that should work :)

**Comment by lauridskern** [comment]
Hi, can anyone help me to get this to work?
This is how I tried the structure:
```JSX
<CarouselProvider>
()=>{
const carouselContext = useContext(CarouselContext);
...
return(
<Slider>slidercontent using {currentSlide}...</Slider>
)}
</MyComponent>
</CarouselProvider>
```

**Comment by theone3nu** [comment]
Any example please i face the same problem i am getting carouselContext as undefined. How to wrap this in my carousel component.

**Comment by theone3nu** [comment]
Here is the example
`  
const Carousel = ({ schools, onSchoolHover }) => {
    
    return (
        <CarouselProvider
            totalSlides={employers.length}
            naturalSlideWidth={1}
            naturalSlideHeight={1}
        >
            <Slider>
                {schools.map((school, index) => {
                    return (
                        <Slide className="custom-slider-height" index={index}>
                           
                        </Slide>
                    )
                }
                )}

            </Slider>
                    <CarouselContextComponent onSliderChange={onSchoolHover }/>
           
        </CarouselProvider>
    )
}

export default Carousel;`

**Comment by alundiak** [comment]
According to [React docs](https://reactjs.org/docs/context.html#contextconsumer) 
> "A React component that subscribes to context changes. Using this component lets you subscribe to a context within a function component. Requires a function as a child. The function receives the current context value and returns a React node. The value argument passed to the function will be equal to the value prop **of the closest Provider for this context above in the tree**. If there is no Provider for this context above, the value argument will be equal to the defaultValue that was passed to createContext()."

Co consider I have `MyCarouselComponent>` which is implemented inside using `<CarouselProvider>` so I technically cant rely on context, when I am OUTSIDE of that component.

So here is quite the same code as in README as as above by @theone3nu (which wasn't working due to error, but it's simple.)

```
TBD
```

My another idea was to inject inside of my component context `Consumer`, custom function to intercept Slide change event.

```
<CarouselContext.Consumer>
                {(value) => {
                  console.log(value.state.currentSlide);
                  return <div>XYZ</div>
                }}
</CarouselContext.Consumer>
```

But it works ONLY at the first phase. Later on, when Slider change, it doesn't cause a context to be mutated/changed, so my `(value)` is NOT changing. It also means, that initial context value is undefined (explains what mention @AgtLucas in description), and as result I can't rely on CarouselConsumer. 

But when I look to React Chrome dev tool, `CarouselConsumer.state {}` IS changed:



I am not sure, but looks like bug in Carousel code.

**Comment by mglavall** [comment]
I'm at the same position as @alundiak. It's a really common use case. Let me know if I can help
