### ISSUE TITLE
Possible to Add Margin to Slides?

### ISSUE THREAD

**Issue by triniMahn** [express-labs/pure-react-carousel#36]
I'm attempting to add some space between the slides (margin-right of 5px), but when I add any margin at all, the 3rd slide (of 3) becomes visible and falls below the first two slides.

Is it possible to add space between the slides? If so, what's the correct way to do so?

Thanks in advance for your assistance. This is a great component.

**Comment by tim-steele** [comment]
@triniMahn We achieve this on express.com. If you go to a product page on a mobile device on express.com, the image have space in between them.

We use padding instead of margin, and we apply the padding to the `carousel__inner-slide` class/InnerTag component, and not the Slide.

The <Slide> component has an `innerClassName` property that you can pass a class name to the InnerTag component, if you don't want to use the `carousel__inner-slide` global class name. By applying `padding-right: 5px` to that, you should be able to get spacing.

**Comment by triniMahn** [comment]
@tim-steele Thank you for your prompt reply!

Despite observing it working for the express.com example, adding your suggested padding to `carousel__inner-slide` broke the overall layout of the component in the same way (i.e. cards wrapping/falling below and overlap of other elements) as adding a margin.

I was, however, able to achieve the desired spacing by putting a div within the `<Slide>` component with a width of 95%. Once we have a publicly accessible version, I will share the URL here.

As for your site, express.com, it seems you have some sort of geo-location logic that will redirect "express.com" to "express.com/canada" (I am in Canada, btw), which in various browsers and over various connections leads the browser to report a "too many redirects" error. To get to your site, I had to search "express com" and then access via some of the site links in Google search.

Thanks again for your help.

**Comment by tim-steele** [comment]
@triniMahn thanks for calling that to our attention. We will look into the redirect issue. I am closing this unless you have any further questions about the margin/padding.
