### ISSUE TITLE
Remove slide snap 

### ISSUE THREAD

**Issue by jmj90** [express-labs/pure-react-carousel#362]
Is there a way to remove the snapping transition between slides? Instead of the slide animating to the next one fully, a user would have total control of how much or little of the slide is revealed. I've tried manipulating the animation classes and attaching custom classes to the carousel and slider but I cant disable the snapping animation.

Context: using the carousel as a horizontal  scroller that contains clickable icons 

![Screen Shot 2021-05-07 at 4 17 10 PM](https://user-images.githubusercontent.com/31748121/117509390-c6f2a500-af4f-11eb-9fdb-2adcd476a271.png)

Thanks

**Comment by captnstarburst** [comment]
Hey, @jmj90 I believe this is the same concern as the issue outlined here [Issue #86 ](https://github.com/express-labs/pure-react-carousel/issues/86). Is this correct? If it is, we still have that listed as WIP and it is currently in a backlog status. You are more than welcome to open a PR addressing this. If I have misunderstood feel free to reopen this issue but since it seems it is the same as #86 I am gonna close it as duplicate :).
