### ISSUE TITLE
Change number of visible slides for tablet/mobile?

### ISSUE THREAD

**Issue by getnorthern** [express-labs/pure-react-carousel#37]
I'd like to be able to display 3 slides on desktop, two on tablet, and one on mobile.

Is it possible to do this?

Also, I've noticed that when displaying 3 slides, 3 of the slides and the corresponding dots are marked as selected - is it possible to mark only the central slide/dot as selected?

Thanks.

**Comment by mrbinky3000** [comment]
@getnorthern You can change the number of slides by changing the visibleSlides property of the CarouselProvider component.

I would write some code that changes the visibleSlides property based on the width of your device. There are tons of ways to find out the device width. I'm sure someone wrote an npm module if you don't know how.  I'll leave that up to you to discover.

As for the dots.  In your case, I would not use the DotGroup component.  I would write my own version of the DotGroup component.  Let's call it, CustomDotGroup.  

You'll need to wrap your CustomDotGroup component in a higher order component that grabs the values for visibleSlides, totalSlides, and currentSlide from the context that CarouselProvider creates. (context is another way React passes data between components). We already do this in each component's index.js file.   For example, here is the index.js file for DotGroup.

```
import DotGroup from './DotGroup';
import WithStore from '../Store/WithStore';

export default WithStore(DotGroup, state => ({
  currentSlide: state.currentSlide,
  totalSlides: state.totalSlides,
  visibleSlides: state.visibleSlides,
}));
```

You'd want to change DotGroup to CustomDotGroup.  But basically, you'd use our WithStore HOC (higher order component) to wrap your CustomDotGroup component so that currentSlide, totalSlides, and visibleSlides are passed as props to your CustomDotGroup component.

CustomDotGroup would loop from 0 to the totalSlides property and create a Dot each iteration.  I would then manually set the disabled property on each Dot component.  You'd have to do some math to determine the center slide.  Your math would need to use visibleSlides, totalSlides, and currentSlide.  

For example, if visibleSlides is 3 (desktop) and currentSlide always points to the left-most visible slide (see the documentation), then you would want to set disabled=false on every dot except for currentSlide +1

**Comment by mrbinky3000** [comment]
I'm going to close this question for now.  Let me know if you need any further explanation.

**Comment by getnorthern** [comment]
Thanks for such a detailed explanation. The number of displayed slides, I’ve already managed to sort - pretty much as you’ve suggested.

I’ll take a look at the dots.

Thanks again!
