### ISSUE TITLE
Pass slide props to children

### ISSUE THREAD

**Issue by ryanlward** [express-labs/pure-react-carousel#43]
I would like to be able to access the slide props in the component that is the child of a slide. For my use case I want to know the index and the position of the slide.

**Comment by codepressd** [comment]
I'm also in need of knowing the current active slide. I know you can set currentSlide but would be nice to know the position of the last current slide.

**Comment by TheFullResolution** [comment]
You could theoretically use `WithStore`:

```
const Logger = ({ slide }) => (
  <div>{slide}</div>
)

const WLogger = WithStore(Logger, (state) => ({
  slide: state.currentSlide
}))
```

The problem is that currently WithStore is not added to default exports, so you can try:

```
import { WithStore } from 'pure-react-carousel/src/Store/WithStore'
```

However, your loader setup would have to be adjusted so the file gets transpiled. I guess the code can be easily adjusted in a future release to accommodate this functionality.

**Comment by tuntisz** [comment]
It would be nice to have this functionality be more accessible. Thank you for your work on pure react carousel, it's been a pleasure to use.

**Comment by mrbinky3000** [comment]
Added in v1.10.0
